# Generated by Django 3.2.6 on 2021-08-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=1000)),
                ('user_password', models.CharField(max_length=1000)),
                ('user_first_name', models.CharField(max_length=1000)),
                ('user_email', models.EmailField(max_length=1000)),
                ('user_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=1000)),
                ('task_priority', models.IntegerField()),
                ('task_description', models.TextField()),
                ('task_attendees', models.IntegerField()),
                ('task_date_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.users')),
            ],
        ),
    ]
