# Generated by Django 3.2.6 on 2021-08-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
