# Generated by Django 3.2.6 on 2021-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_user_id_tasks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_password',
            new_name='user_hash',
        ),
        migrations.AddField(
            model_name='users',
            name='user_salt',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
