# Generated by Django 3.2.6 on 2021-08-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_auto_20210827_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_login',
        ),
    ]
