# Generated by Django 3.2.6 on 2021-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_remove_users_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
