# Generated by Django 3.2.6 on 2021-09-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0008_tasks_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_attendees',
        ),
    ]
