# Generated by Django 3.2.6 on 2021-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_remove_tasks_task_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
