# Generated by Django 3.2.6 on 2021-09-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0011_rename_user_first_name_users_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTasks',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='to_do_list.tasks')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='to_do_list.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='to_do_list.users')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='to_do_list.users')),
                ('friend', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='to_do_list.users')),
            ],
        ),
    ]
