# Generated by Django 3.2.6 on 2021-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0012_friendslist_sharedtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('specified_date_time', models.DateTimeField()),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee_status', to='to_do_list.friendship')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_status', to='to_do_list.friendship')),
            ],
        ),
        migrations.CreateModel(
            name='MyStatus',
            fields=[
                ('status_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
        migrations.AddField(
            model_name='friendshipstatus',
            name='specifier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.users'),
        ),
        migrations.AddField(
            model_name='friendshipstatus',
            name='status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.mystatus'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='to_do_list.users'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='to_do_list.users'),
        ),
    ]
