# Generated by Django 3.2.6 on 2021-09-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0013_auto_20210909_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshipstatus',
            old_name='addressee',
            new_name='addressee_status',
        ),
        migrations.RenameField(
            model_name='friendshipstatus',
            old_name='requester',
            new_name='requester_status',
        ),
    ]
