# Generated by Django 3.2.6 on 2021-09-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0015_auto_20210909_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='addressee',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='specifier_id',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='status_code',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipStatus',
        ),
        migrations.DeleteModel(
            name='MyStatus',
        ),
    ]
