# Generated by Django 3.2.6 on 2021-09-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0017_friendship_friendshipstatus_mystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='addressee_status',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='requester_status',
        ),
        migrations.AddField(
            model_name='friendshipstatus',
            name='addressee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addressee_id', to='to_do_list.friendship'),
        ),
        migrations.AddField(
            model_name='friendshipstatus',
            name='requester_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requester_id', to='to_do_list.friendship'),
        ),
        migrations.AlterField(
            model_name='friendshipstatus',
            name='specified_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
