# Generated by Django 3.2.6 on 2021-09-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0018_auto_20210910_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='addressee_id',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='requester_id',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='specifier_id',
        ),
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='status_code',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipStatus',
        ),
        migrations.DeleteModel(
            name='MyStatus',
        ),
    ]
