# Generated by Django 3.2.6 on 2021-09-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0019_auto_20210910_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friends', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='to_do_list.users')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='to_do_list.users')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendStatus',
            fields=[
                ('friends_status', models.AutoField(primary_key=True, serialize=False)),
                ('specified_datetime', models.DateTimeField(auto_now_add=True)),
                ('friends_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.friends')),
                ('specifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.users')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.status')),
            ],
        ),
    ]
