# Generated by Django 3.2.6 on 2021-09-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0020_friends_friendstatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendStatus',
        ),
    ]
