# Generated by Django 3.2.6 on 2021-09-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0021_delete_friendstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsStatus',
            fields=[
                ('friends_status', models.AutoField(primary_key=True, serialize=False)),
                ('specified_datetime', models.DateTimeField(auto_now_add=True)),
                ('friends_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.friends')),
                ('specifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.users')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.status')),
            ],
        ),
    ]
