# Generated by Django 3.2.6 on 2021-09-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0022_friendsstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsstatus',
            name='friends_id',
        ),
        migrations.RemoveField(
            model_name='friendsstatus',
            name='specifier_id',
        ),
        migrations.RemoveField(
            model_name='friendsstatus',
            name='status_code',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='FriendsStatus',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
