# Generated by Django 3.2.6 on 2021-09-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0023_auto_20210910_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
